/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* I2C_BUS_scl */
#define I2C_BUS_scl_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_BUS_scl_0_INBUF_ENABLED 1u
#define I2C_BUS_scl_0_INIT_DRIVESTATE 1u
#define I2C_BUS_scl_0_INIT_MUXSEL 19u
#define I2C_BUS_scl_0_INPUT_SYNC 2u
#define I2C_BUS_scl_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_BUS_scl_0_NUM 4u
#define I2C_BUS_scl_0_PORT GPIO_PRT6
#define I2C_BUS_scl_0_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_BUS_scl_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define I2C_BUS_scl_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_BUS_scl_INBUF_ENABLED 1u
#define I2C_BUS_scl_INIT_DRIVESTATE 1u
#define I2C_BUS_scl_INIT_MUXSEL 19u
#define I2C_BUS_scl_INPUT_SYNC 2u
#define I2C_BUS_scl_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_BUS_scl_NUM 4u
#define I2C_BUS_scl_PORT GPIO_PRT6
#define I2C_BUS_scl_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_BUS_scl_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* I2C_BUS_sda */
#define I2C_BUS_sda_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_BUS_sda_0_INBUF_ENABLED 1u
#define I2C_BUS_sda_0_INIT_DRIVESTATE 1u
#define I2C_BUS_sda_0_INIT_MUXSEL 19u
#define I2C_BUS_sda_0_INPUT_SYNC 2u
#define I2C_BUS_sda_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_BUS_sda_0_NUM 5u
#define I2C_BUS_sda_0_PORT GPIO_PRT6
#define I2C_BUS_sda_0_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_BUS_sda_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define I2C_BUS_sda_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_BUS_sda_INBUF_ENABLED 1u
#define I2C_BUS_sda_INIT_DRIVESTATE 1u
#define I2C_BUS_sda_INIT_MUXSEL 19u
#define I2C_BUS_sda_INPUT_SYNC 2u
#define I2C_BUS_sda_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_BUS_sda_NUM 5u
#define I2C_BUS_sda_PORT GPIO_PRT6
#define I2C_BUS_sda_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_BUS_sda_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Uart_Printf_rx */
#define Uart_Printf_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Uart_Printf_rx_0_INBUF_ENABLED 1u
#define Uart_Printf_rx_0_INIT_DRIVESTATE 1u
#define Uart_Printf_rx_0_INIT_MUXSEL 18u
#define Uart_Printf_rx_0_INPUT_SYNC 2u
#define Uart_Printf_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Uart_Printf_rx_0_NUM 0u
#define Uart_Printf_rx_0_PORT GPIO_PRT5
#define Uart_Printf_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Uart_Printf_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Uart_Printf_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Uart_Printf_rx_INBUF_ENABLED 1u
#define Uart_Printf_rx_INIT_DRIVESTATE 1u
#define Uart_Printf_rx_INIT_MUXSEL 18u
#define Uart_Printf_rx_INPUT_SYNC 2u
#define Uart_Printf_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Uart_Printf_rx_NUM 0u
#define Uart_Printf_rx_PORT GPIO_PRT5
#define Uart_Printf_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define Uart_Printf_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Uart_Printf_tx */
#define Uart_Printf_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Uart_Printf_tx_0_INBUF_ENABLED 0u
#define Uart_Printf_tx_0_INIT_DRIVESTATE 1u
#define Uart_Printf_tx_0_INIT_MUXSEL 18u
#define Uart_Printf_tx_0_INPUT_SYNC 2u
#define Uart_Printf_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Uart_Printf_tx_0_NUM 1u
#define Uart_Printf_tx_0_PORT GPIO_PRT5
#define Uart_Printf_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Uart_Printf_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Uart_Printf_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Uart_Printf_tx_INBUF_ENABLED 0u
#define Uart_Printf_tx_INIT_DRIVESTATE 1u
#define Uart_Printf_tx_INIT_MUXSEL 18u
#define Uart_Printf_tx_INPUT_SYNC 2u
#define Uart_Printf_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Uart_Printf_tx_NUM 1u
#define Uart_Printf_tx_PORT GPIO_PRT5
#define Uart_Printf_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define Uart_Printf_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
